services:
  db:
    image: mongo:8.3.4-noble
    container_name: mongodb
    restart: unless-stopped

    environment:
      MONGO_ADMIN_USER: ${MONGO_ADMIN_USER}
      MONGO_ADMIN_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

    networks:
      - backend

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db
      - ./backEnd/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  epitransfert:
    build: backEnd
    container_name: epitransfert

    depends_on:
      db:
        condition: service_healthy

    environment:
      MONGO_ADMIN_USER: ${MONGO_ADMIN_USER}
      MONGO_ADMIN_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

    networks:
      - backend

    ports:
      - 8080:8080

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data: {}
